import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import axios from 'axios';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import Header from '@/components/Header';
import { ArrowLeft, Eye, Edit3, Upload, Bold, Italic, Underline, Type, AlignLeft, AlignCenter, AlignRight, CheckCircle } from 'lucide-react';
import { IMaskInput } from 'react-imask';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const CreateContractPage = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const templateId = searchParams.get('template_id');
  
  const [loading, setLoading] = useState(false);
  const [loadingTemplate, setLoadingTemplate] = useState(false);
  const token = localStorage.getItem('token');
  
  // Template data from marketplace
  const [selectedTemplate, setSelectedTemplate] = useState(null);
  const [placeholderValues, setPlaceholderValues] = useState({});
  
  // Next contract number (for display)
  const [nextContractNumber, setNextContractNumber] = useState(null);
  
  // Manual editing mode
  const [manualEditMode, setManualEditMode] = useState(false);
  const [manualContent, setManualContent] = useState('');
  const [isContentSaved, setIsContentSaved] = useState(false);
  
  // Optional fields visibility
  const [showOptionalFields, setShowOptionalFields] = useState(false);
  
  // Tenant document upload (optional for landlord to upload)
  const [tenantDocument, setTenantDocument] = useState(null);
  const [tenantDocPreview, setTenantDocPreview] = useState(null);
  const [uploadingDoc, setUploadingDoc] = useState(false);
  
  // Template fields
  const [templateData, setTemplateData] = useState({
    // Contract info - contract_number will be generated by backend
    contract_date: new Date().toISOString().split('T')[0],
    
    // Landlord (Creator) info
    landlord_name: 'ИП "RentDomik"',
    landlord_representative: '', // Кто составил договор
    
    // Tenant (Signer) info
    tenant_name: '',
    tenant_phone: '',
    tenant_email: '',
    
    // Property details
    property_address: '',
    
    // Financial terms
    rent_amount: '',
    rent_currency: 'тенге',
    security_deposit: '',
    
    // Dates
    move_in_date: '',
    move_out_date: '',
    
    // Additional terms
    days_count: '0',
    payment_method: 'наличными',
    
    // Contract type
    contract_type: 'rent' // rent, service, purchase
  });

  // Calculate days automatically
  const calculateDays = (moveIn, moveOut) => {
    if (!moveIn || !moveOut) return 0;
    
    // Parse dates and set times: check-in at 14:00, check-out at 12:00
    const checkInDate = new Date(moveIn);
    checkInDate.setHours(14, 0, 0, 0);
    
    const checkOutDate = new Date(moveOut);
    checkOutDate.setHours(12, 0, 0, 0);
    
    // Calculate difference in milliseconds
    const diffMs = checkOutDate - checkInDate;
    
    // Convert to days (1 day = 24 hours = 86400000 ms)
    const days = Math.ceil(diffMs / (1000 * 60 * 60 * 24));
    
    return days > 0 ? days : 0;
  };

  const handleFieldChange = (field, value) => {
    setTemplateData(prev => {
      const newData = { ...prev, [field]: value };
      
      // Auto-calculate days when dates change
      if (field === 'move_in_date' || field === 'move_out_date') {
        newData.days_count = calculateDays(
          field === 'move_in_date' ? value : prev.move_in_date,
          field === 'move_out_date' ? value : prev.move_out_date
        ).toString();
      }
      
      return newData;
    });
  };

  const editorRef = useRef(null);

  // Load next contract number on mount
  useEffect(() => {
    const fetchNextContractNumber = async () => {
      try {
        const response = await axios.get(`${API}/contracts`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        const contractCount = response.data.length;
        const nextNumber = `0${contractCount + 1}`;
        setNextContractNumber(nextNumber);
      } catch (error) {
        console.error('Error fetching contract count:', error);
      }
    };
    
    fetchNextContractNumber();

    // Load template if template_id is provided
    if (templateId) {
      loadTemplateFromMarket(templateId);
    }
  }, [templateId]);

  const loadTemplateFromMarket = async (id) => {
    setLoadingTemplate(true);
    try {
      const response = await axios.get(`${API}/templates/${id}`);
      const template = response.data;
      
      setSelectedTemplate(template);
      setManualContent(template.content || '');
      
      // Initialize placeholder values
      const initialValues = {};
      if (template.placeholders) {
        Object.keys(template.placeholders).forEach(key => {
          initialValues[key] = '';
        });
      }
      setPlaceholderValues(initialValues);
      
      toast.success(`Шаблон "${template.title}" загружен`);
    } catch (error) {
      console.error('Error loading template:', error);
      toast.error('Ошибка загрузки шаблона');
    } finally {
      setLoadingTemplate(false);
    }
  };

  const loadLastTemplate = () => {
    try {
      const savedTemplate = localStorage.getItem('signify_last_template');
      if (!savedTemplate) {
        toast.info('Нет сохраненного шаблона');
        return;
      }
      
      const template = JSON.parse(savedTemplate);
      
      // Restore template data (excluding contract_number and contract_date)
      setTemplateData(prev => ({
        ...prev,
        landlord_name: template.landlord_name || prev.landlord_name,
        landlord_representative: template.landlord_representative || prev.landlord_representative,
        tenant_name: template.tenant_name || '',
        tenant_phone: template.tenant_phone || '',
        tenant_email: template.tenant_email || '',
        property_address: template.property_address || prev.property_address,
        rent_amount: template.rent_amount || prev.rent_amount,
        rent_currency: template.rent_currency || prev.rent_currency,
        security_deposit: template.security_deposit || prev.security_deposit,
        move_in_date: template.move_in_date || prev.move_in_date,
        move_out_date: template.move_out_date || prev.move_out_date,
        days_count: template.days_count || prev.days_count,
        payment_method: template.payment_method || prev.payment_method,
        contract_type: template.contract_type || prev.contract_type
      }));
      
      // Restore saved content if exists
      if (template.isContentSaved && template.savedContent) {
        setManualContent(template.savedContent);
        setIsContentSaved(true);
      }
      
      const savedDate = new Date(template.savedAt).toLocaleString('ru-RU');
      toast.success(`Шаблон загружен (сохранен ${savedDate})`);
    } catch (error) {
      console.error('Error loading template:', error);
      toast.error('Ошибка при загрузке шаблона');
    }
  };

  const toggleEditMode = () => {
    if (!manualEditMode) {
      // If content was already saved, use it; otherwise generate new
      if (!isContentSaved) {
        const content = generatePreviewContent();
        // Просто конвертируем переносы строк в <br>, БЕЗ подсветки
        setManualContent(content.replace(/\n/g, '<br>'));
      }
      // Если isContentSaved = true, manualContent уже содержит сохраненный контент
    }
    setManualEditMode(!manualEditMode);
  };

  const handleSaveContent = () => {
    if (editorRef.current) {
      const savedContent = editorRef.current.innerHTML;
      setManualContent(savedContent);
      setIsContentSaved(true);
      setManualEditMode(false); // Return to form after saving
      toast.success('Изменения сохранены!');
    }
  };

  const executeCommand = (command, value = null) => {
    document.execCommand(command, false, value);
  };

  const changeFontSize = (size) => {
    document.execCommand('fontSize', '7');
    const fontElements = editorRef.current?.querySelectorAll('font[size="7"]');
    fontElements?.forEach(el => {
      el.removeAttribute('size');
      el.style.fontSize = size;
    });
  };

  const handleTenantDocUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setTenantDocument(file);
    
    // Create preview
    const reader = new FileReader();
    reader.onloadend = () => {
      setTenantDocPreview(reader.result);
    };
    reader.readAsDataURL(file);
    
    toast.success('Документ клиента выбран');
  };


  const formatDateToDDMMYYYY = (dateStr) => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    const day = String(date.getDate()).padStart(2, '0');
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const year = date.getFullYear();
    return `${day}.${month}.${year}`;
  };

  const generatePreviewContent = () => {
    // If template is selected, use template content with replaced placeholders
    if (selectedTemplate && selectedTemplate.content) {
      let content = selectedTemplate.content;
      
      // Replace placeholders with actual values
      if (selectedTemplate.placeholders) {
        Object.entries(selectedTemplate.placeholders).forEach(([key, config]) => {
          let value = placeholderValues[key] || `[${config.label}]`;
          
          // Format dates to DD.MM.YYYY
          if (config.type === 'date' && placeholderValues[key]) {
            value = formatDateToDDMMYYYY(placeholderValues[key]);
          }
          
          const regex = new RegExp(`{{${key}}}`, 'g');
          
          // For calculated fields, compute the value
          if (config.type === 'calculated' && config.formula) {
            const { operand1, operation, operand2 } = config.formula;
            
            let result = 0;
            
            if (operation === 'days_between') {
              // Date calculation
              if (placeholderValues[operand1] && placeholderValues[operand2]) {
                const date1 = new Date(placeholderValues[operand1]);
                const date2 = new Date(placeholderValues[operand2]);
                const diffTime = Math.abs(date2 - date1);
                result = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
              }
            } else {
              // Numerical calculation
              const val1 = parseFloat(placeholderValues[operand1]) || 0;
              const val2 = parseFloat(placeholderValues[operand2]) || 0;
              
              switch(operation) {
                case 'add': result = val1 + val2; break;
                case 'subtract': result = val1 - val2; break;
                case 'multiply': result = val1 * val2; break;
                case 'divide': result = val2 !== 0 ? val1 / val2 : 0; break;
                case 'modulo': result = val2 !== 0 ? val1 % val2 : 0; break;
                default: result = 0;
              }
            }
            
            content = content.replace(regex, result.toString() || `[${config.label}]`);
          } else {
            content = content.replace(regex, value);
          }
        });
      }
      
      return content;
    }
    
    // Fallback to old template generation
    return generateContractContent();
  };

  const generateContractContent = () => {
    const { 
      contract_date,
      landlord_name,
      landlord_representative,
      tenant_name,
      property_address,
      rent_amount,
      rent_currency,
      security_deposit,
      move_in_date,
      move_out_date,
      days_count,
      payment_method
    } = templateData;

    return `ДОГОВОР КРАТКОСРОЧНОГО НАЙМА ЖИЛОГО ПОМЕЩЕНИЯ

${contract_date}

Мы, нижеподписавшиеся, ${landlord_name}, именуемый в дальнейшем «Наймодатель», с одной стороны, и гражданин ${tenant_name || '[ФИО Нанимателя]'} (ОКПО трлнатт.ндт), именуемый в дальнейшем «Наниматель», с другой стороны, совместно именуемые «Стороны», заключили настоящий Договор о нижеследующем:

1. Предмет Договора

1.1. Наймодатель предоставляет, а Наниматель принимает во временное платное пользование жилое помещение по адресу: ${property_address || '[Адрес квартиры]'}.

1.2. Жилое помещение передается в найм на срок с ${move_in_date || '[Дата заселения]'} по ${move_out_date || '[Дата выселения]'}, что составляет ${days_count || '[Количество суток]'} суток.

Дата заселения: с 14:00, ${move_in_date || '[Дата заселения]'}
Дата выселения: до 12:00, ${move_out_date || '[Дата выселения]'}

1.3. Право распоряжаться и пользоваться жилым помещением подтверждается следующими документами: Договор долевременного управления.

1.4. Помимо Нанимателя в жилом помещении будет проживать: ${days_count || '[Кто еще будет проживать]'}.

2. Плата за найм

2.1. За пользование жилым помещением устанавливается плата в размере ${rent_amount || '[Цена в сутки]'} ${rent_currency} в сутки.

2.2. При бронировании вносится предоплата за бронь в размере ${security_deposit || '[Оплачено]'}.

2.3. Полная стоимость за указанные даты - ${rent_amount ? (parseInt(rent_amount) * parseInt(days_count || 1)) : '[Полная стоимость]'} ${rent_currency}. Данная сумма уплачивается Нанимателем и полном объеме при заселении в жилое помещение или заранее безналичным способом.

2.4. При въезде вносится обеспечительный платёж в размере ${security_deposit || '[Обеспечительный депозит]'}, за сохранность имущества и полном объеме при выселении. Данный платёж возвращается в полном объеме при выселении.

2.5. Для целей настоящего Договора исчисление каждых суток найма начинается с 14.30, в случае более позднего заселения со дня и часа заселения. Неполные сутки найма, образовавшиеся в случае заселения позднее 14.30 или выселения ранее 12.00, оплачиваются пропорционально времени фактического проживания, но не менее 50% суточной платы за найм увеличивается согласно тарифа.

2.6. В состав платы за найм расходов Наймодателя по оплате коммунальных услуг.

2.7. В случае досрочного расторжения, ранее оговоренных сроков найма жилого помещения, сумма арендной платы по согласованию сторон может быть пересчитана без объяснения причин, оплаченные денежные средства за проживание не возвращаются.

3. Права и обязанности сторон

3.1. Права и обязанности Наймодателя:

3.1.1. Наймодатель обязуется предоставить Нанимателю пользование жилым помещением вместе с мебелью, необходимой бытовой техникой, посудой, кухонными принадлежностями и постельным бельем.

3.1.2. Передать Нанимателю полный комплект ключей от жилого помещения, подъезда и этажа, и в случае если таковой утерян или оставлен внутри помещения без возможности открыть снаружи.

3.1.3. Устранить в жилом помещении поломки, аварии и неисправности, произошедшие не по вине Нанимателя.

3.1.4. Наймодатель имеет право осуществлять проверку порядка использования Нанимателем жилого помещения без согласования с Нанимателем.

3.2. Права и обязанности Нанимателя:

3.2.1. Наниматель вправе пользоваться жилым помещением, мебелью, бытовой техникой, нарушать права и интересов соседей, а также поддерживать жилое помещение в состоянии.

3.2.2. Бережно относиться к имуществу Наймодателя, находящемуся в жилом помещении.

3.2.3. При досрочном прекращении Договора досрочно Наймодателю полученный комплект ключей.

3.2.4. При выселении жилого помещения в состояние, в котором оно было на момент вселения, за исключением нормального износа. В случае малой соседей, жилое помещение подлежит санитарной уборке силами Нанимателя. Перед отъездом следует выселение без возврата в случае ненадлежащего состояния жилого помещения.

3.2.5. В случае, если Нанимателем запрещено проведение шумных мероприятий. В случае жалоб соседей, следует выселение без возврата.

3.2.6. Запрещено проживание в жилом помещении лиц, не указанных в настоящем Договоре. В случае нарушения этого правила, следует выселение без возврата.

3.2.7. Запрещено курение в жилом помещении. В случае выявления запрещается арендаторские средства.

4. Порядок передачи и возврата жилого помещения

4.1. При передаче жилого помещения техническое и внешнее состояние предмета осуществляется осмотр посредством приема-передачи жилого помещения на момент передачи написаны претензии. Прием жилого помещения осуществляется Нанимателем лично, посредством электронной почты или через Ватсап в течении 2 часов после заселения.

4.2. При выселении жилого помещения Наниматель должен вернуть его в состоянии, в котором он получил, за исключением нормального износа. Санитарное состояние жилого помещения должно быть удовлетворительным.

5. Ответственность Сторон

5.1. За неисполнение или ненадлежащее исполнение обязательств по настоящему Договору Стороны несут ответственность в соответствии с законодательством.

6. Прочие условия

6.1. Настоящий Договор составлен в двух экземплярах, имеющих одинаковую юридическую силу, по одному для каждой из Сторон.

6.2. Споры по настоящему Договору разрешаются путем переговоров, а при недостижении согласия — в судебном порядке.

7. Реквизиты и подписи Сторон

Наймодатель: ${landlord_name}
Представитель: ${landlord_representative || '[Представитель]'}

Наниматель: ${tenant_name || '[ФИО]'}
Телефон: ${templateData.tenant_phone || '[Телефон]'}
Email: ${templateData.tenant_email || '[Email]'}

Подписи:

Наймодатель: _____________
Наниматель: _____________

Дата: ${contract_date}`;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    
    try {
      // Use saved content if available, otherwise generate from form
      let contentToSave = isContentSaved ? manualContent : (selectedTemplate ? selectedTemplate.content : generateContractContent());
      
      // Replace placeholders with actual values
      if (selectedTemplate && placeholderValues) {
        Object.entries(placeholderValues).forEach(([key, value]) => {
          const regex = new RegExp(`{{${key}}}`, 'g');
          contentToSave = contentToSave.replace(regex, value || `[${key}]`);
        });
        
        // Calculate computed fields
        if (selectedTemplate.placeholders) {
          Object.entries(selectedTemplate.placeholders).forEach(([key, config]) => {
            if (config.type === 'calculated' && config.formula) {
              const { operand1, operation, operand2 } = config.formula;
              const val1 = parseFloat(placeholderValues[operand1]) || 0;
              const val2 = parseFloat(placeholderValues[operand2]) || 0;
              
              let result = 0;
              switch(operation) {
                case 'add': result = val1 + val2; break;
                case 'subtract': result = val1 - val2; break;
                case 'multiply': result = val1 * val2; break;
                case 'divide': result = val2 !== 0 ? val1 / val2 : 0; break;
                case 'modulo': result = val2 !== 0 ? val1 % val2 : 0; break;
                case 'days_between':
                  const date1 = new Date(placeholderValues[operand1]);
                  const date2 = new Date(placeholderValues[operand2]);
                  result = Math.abs(Math.ceil((date2 - date1) / (1000 * 60 * 60 * 24)));
                  break;
                default: result = 0;
              }
              
              const regex = new RegExp(`{{${key}}}`, 'g');
              contentToSave = contentToSave.replace(regex, result.toString());
            }
          });
        }
      }
      
      // Store metadata about whether content is HTML or plain text
      const isHtmlContent = isContentSaved && manualContent.includes('<');
      
      // Extract tenant info from placeholders or templateData
      let signerName = templateData.tenant_name;
      let signerPhone = templateData.tenant_phone;
      let signerEmail = templateData.tenant_email;
      
      if (selectedTemplate && selectedTemplate.placeholders) {
        // Try to find tenant info in placeholders
        Object.entries(selectedTemplate.placeholders).forEach(([key, config]) => {
          const value = placeholderValues[key];
          if (config.type === 'text' && (key.toLowerCase().includes('tenant') || key.toLowerCase().includes('наниматель'))) {
            signerName = value || signerName;
          } else if (config.type === 'phone') {
            signerPhone = value || signerPhone;
          } else if (config.type === 'email') {
            signerEmail = value || signerEmail;
          }
        });
      }
      
      const contractData = {
        title: selectedTemplate ? selectedTemplate.title : `Договор от ${templateData.contract_date}`,
        content: contentToSave,
        content_type: selectedTemplate ? selectedTemplate.content_type : (isHtmlContent ? 'html' : 'plain'),
        source_type: selectedTemplate ? 'template' : 'manual',
        template_id: selectedTemplate ? selectedTemplate.id : undefined,
        signer_name: signerName || 'Не указано',
        signer_phone: signerPhone || '',
        signer_email: signerEmail,
        move_in_date: templateData.move_in_date,
        move_out_date: templateData.move_out_date,
        property_address: templateData.property_address,
        rent_amount: templateData.rent_amount,
        days_count: templateData.days_count,
        amount: templateData.rent_amount ? `${parseInt(templateData.rent_amount) * parseInt(templateData.days_count || 1)} ${templateData.rent_currency}` : undefined
      };
      
      const response = await axios.post(`${API}/contracts`, contractData, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      const contractId = response.data.id;
      const contractNumber = response.data.contract_number;  // Get contract number from backend
      
      // Update contract title with proper contract number from backend
      if (contractNumber) {
        await axios.put(`${API}/contracts/${contractId}`, 
          { title: `Договор № ${contractNumber} от ${templateData.contract_date}` },
          { headers: { Authorization: `Bearer ${token}` }}
        );
      }
      
      // Save template to localStorage for future use
      const templateToSave = {
        ...templateData,
        savedContent: isContentSaved ? manualContent : null,
        isContentSaved: isContentSaved,
        savedAt: new Date().toISOString()
      };
      localStorage.setItem('signify_last_template', JSON.stringify(templateToSave));
      
      // Upload tenant document if selected (optional)
      if (tenantDocument) {
        setUploadingDoc(true);
        const formData = new FormData();
        formData.append('file', tenantDocument);
        
        try {
          await axios.post(`${API}/sign/${contractId}/upload-document`, formData);
          toast.success('Договор и документ клиента успешно созданы');
        } catch (docError) {
          console.error('Document upload error:', docError);
          toast.warning('Договор создан, но документ клиента не загружен');
        } finally {
          setUploadingDoc(false);
        }
      } else {
        toast.success(t('common.success'));
      }
      
      navigate(`/contracts/${contractId}`);
    } catch (error) {
      toast.error(error.response?.data?.detail || t('common.error'));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-neutral-50">
      <Header />
      
      <div className="max-w-[1600px] mx-auto px-4 py-8">
        <Button
          variant="ghost"
          onClick={() => navigate('/dashboard')}
          className="mb-6"
          data-testid="back-button"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Dashboard
        </Button>
        
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-neutral-900">{t('contract.create.title')}</h1>
          {loadingTemplate && (
            <div className="mt-3 p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-sm text-blue-800">⏳ Загрузка шаблона...</p>
            </div>
          )}
          {selectedTemplate && (
            <div className="mt-3 p-3 bg-green-50 border border-green-200 rounded-lg">
              <p className="text-sm text-green-800">✓ Шаблон загружен: <strong>{selectedTemplate.title}</strong></p>
            </div>
          )}
          {nextContractNumber && (
            <p className="text-xl font-bold text-neutral-900 mt-3">
              Номер договора: {nextContractNumber}
            </p>
          )}
          <p className="text-neutral-600 mt-2">Заполните поля справа, договор автоматически обновится слева</p>
          <div className="mt-3">
            <Button
              type="button"
              variant="outline"
              onClick={loadLastTemplate}
              className="text-sm"
            >
              📋 Загрузить последний шаблон
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left: Contract Preview */}
          <Card className="lg:sticky lg:top-4 h-fit" data-testid="contract-preview-card">
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle className="flex items-center gap-2">
                <Eye className="h-5 w-5" />
                {manualEditMode ? 'Редактировать договор' : 'Предпросмотр договора'}
                {isContentSaved && !manualEditMode && (
                  <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded">✓ Отредактировано</span>
                )}
              </CardTitle>
              <div className="flex gap-2">
                {!manualEditMode && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={toggleEditMode}
                  >
                    <Edit3 className="h-4 w-4 mr-2" />
                    Редактировать вручную
                  </Button>
                )}
                {manualEditMode && (
                  <Button
                    type="button"
                    variant="default"
                    size="sm"
                    onClick={handleSaveContent}
                  >
                    Сохранить
                  </Button>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {manualEditMode ? (
                <div className="editor-container">
                  {/* Toolbar */}
                  <div className="bg-gray-50 border border-gray-300 rounded-t-lg p-2 flex flex-wrap gap-1 items-center">
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('bold'); }} className="h-8 w-8 p-0" title="Жирный"><Bold className="h-4 w-4" /></Button>
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('italic'); }} className="h-8 w-8 p-0" title="Курсив"><Italic className="h-4 w-4" /></Button>
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('underline'); }} className="h-8 w-8 p-0" title="Подчеркнутый"><Underline className="h-4 w-4" /></Button>
                    
                    <div className="w-px bg-gray-300 mx-1" />
                    
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('formatBlock', '<h1>'); }} className="h-8 px-2" title="Заголовок 1">H1</Button>
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('formatBlock', '<h2>'); }} className="h-8 px-2" title="Заголовок 2">H2</Button>
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('formatBlock', '<h3>'); }} className="h-8 px-2" title="Заголовок 3">H3</Button>
                    
                    <div className="w-px bg-gray-300 mx-1" />
                    
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('justifyLeft'); }} className="h-8 w-8 p-0" title="По левому краю"><AlignLeft className="h-4 w-4" /></Button>
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('justifyCenter'); }} className="h-8 w-8 p-0" title="По центру"><AlignCenter className="h-4 w-4" /></Button>
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('justifyRight'); }} className="h-8 w-8 p-0" title="По правому краю"><AlignRight className="h-4 w-4" /></Button>
                    
                    <div className="w-px bg-gray-300 mx-1" />
                    
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('insertUnorderedList'); }} className="h-8 px-2" title="Маркированный список">• Список</Button>
                    <Button type="button" variant="ghost" size="sm" onMouseDown={(e) => { e.preventDefault(); executeCommand('insertOrderedList'); }} className="h-8 px-2" title="Нумерованный список">1. Список</Button>
                    
                    <div className="w-px bg-gray-300 mx-1" />
                    
                    <select onChange={(e) => changeFontSize(e.target.value)} className="h-8 px-2 border rounded text-sm" defaultValue="14px">
                      <option value="12px">Маленький</option>
                      <option value="14px">Обычный</option>
                      <option value="16px">Большой</option>
                      <option value="18px">Огромный</option>
                    </select>
                  </div>
                  
                  {/* Editor */}
                  <div
                    ref={editorRef}
                    contentEditable
                    dangerouslySetInnerHTML={{ __html: manualContent }}
                    suppressContentEditableWarning
                    key={manualContent}
                    onBlur={(e) => setManualContent(e.currentTarget.innerHTML)}
                    className="min-h-[700px] p-4 border border-t-0 border-gray-300 rounded-b-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    style={{
                      fontFamily: 'IBM Plex Sans, sans-serif',
                      fontSize: '14px',
                      lineHeight: '1.6',
                      overflowY: 'auto'
                    }}
                  />
                </div>
              ) : (
                <div className="bg-white border rounded-lg p-6 max-h-[800px] overflow-y-auto" data-testid="contract-preview">
                  {isContentSaved ? (
                    <div 
                      className="prose prose-sm max-w-none"
                      style={{
                        fontFamily: 'IBM Plex Sans, sans-serif',
                        fontSize: '14px',
                        lineHeight: '1.6'
                      }}
                      dangerouslySetInnerHTML={{ __html: manualContent }}
                    />
                  ) : (
                    <div className="prose prose-sm max-w-none">
                      <pre className="whitespace-pre-wrap text-xs font-['IBM_Plex_Sans'] leading-relaxed text-neutral-800">
                        {generatePreviewContent()}
                      </pre>
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>

          {/* Right: Form Fields */}
          <Card data-testid="contract-form-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Edit3 className="h-5 w-5" />
                Заполните данные
              </CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-6" data-testid="create-contract-form">
                {/* Contract Info */}
                <div className="space-y-4">
                  <h3 className="font-semibold text-neutral-900 border-b pb-2">Информация о договоре</h3>
                  <div className="grid grid-cols-1 gap-4">
                    <div>
                      <Label htmlFor="contract_date">Дата договора *</Label>
                      <Input
                        id="contract_date"
                        type="date"
                        value={templateData.contract_date}
                        onChange={(e) => handleFieldChange('contract_date', e.target.value)}
                        required
                        data-testid="contract-date-input"
                        className="mt-1"
                      />
                      <p className="text-sm text-neutral-500 mt-1">
                        💡 Номер договора будет сгенерирован автоматически (01, 02, 010, 0110...)
                      </p>
                    </div>
                  </div>
                </div>

                {/* Landlord Info */}
                <div className="space-y-4">
                  <h3 className="font-semibold text-neutral-900 border-b pb-2">Наймодатель (Вы)</h3>
                  <div>
                    <Label htmlFor="landlord_name">Наименование *</Label>
                    <Input
                      id="landlord_name"
                      value={templateData.landlord_name}
                      onChange={(e) => handleFieldChange('landlord_name', e.target.value)}
                      required
                      data-testid="landlord-name-input"
                      className="mt-1"
                    />
                  </div>
                  <div>
                    <Label htmlFor="landlord_representative">Представитель (кто составил договор) *</Label>
                    <Input
                      id="landlord_representative"
                      value={templateData.landlord_representative}
                      onChange={(e) => handleFieldChange('landlord_representative', e.target.value)}
                      required
                      data-testid="landlord-rep-input"
                      className="mt-1"
                      placeholder="ФИО"
                    />
                  </div>
                </div>

                {/* Dynamic Template Fields */}
                {selectedTemplate && selectedTemplate.placeholders && Object.keys(selectedTemplate.placeholders).length > 0 && (
                  <div className="space-y-4 p-6 bg-gradient-to-br from-blue-50/50 to-purple-50/50 border-2 border-dashed border-blue-200 rounded-xl">
                    <div className="border-b pb-2">
                      <h3 className="font-semibold text-neutral-900 flex items-center gap-2">
                        📋 Поля шаблона "{selectedTemplate.title}"
                      </h3>
                      <p className="text-xs text-neutral-600 mt-1">
                        Заполните необходимые поля для договора
                      </p>
                    </div>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {Object.entries(selectedTemplate.placeholders).map(([key, config]) => {
                        // Skip calculated fields - they will be computed automatically
                        if (config.type === 'calculated') return null;
                        
                        return (
                          <div key={key} className={config.type === 'text' ? 'md:col-span-2' : ''}>
                            <Label htmlFor={`placeholder_${key}`}>
                              {config.label} {config.required && <span className="text-red-500">*</span>}
                            </Label>
                            
                            {config.type === 'text' && (
                              <Input
                                id={`placeholder_${key}`}
                                value={placeholderValues[key] || ''}
                                onChange={(e) => setPlaceholderValues({...placeholderValues, [key]: e.target.value})}
                                required={config.required}
                                className="mt-1"
                                placeholder={`Введите ${config.label.toLowerCase()}`}
                              />
                            )}
                            
                            {config.type === 'number' && (
                              <Input
                                id={`placeholder_${key}`}
                                type="number"
                                value={placeholderValues[key] || ''}
                                onChange={(e) => setPlaceholderValues({...placeholderValues, [key]: e.target.value})}
                                required={config.required}
                                className="mt-1"
                                placeholder={`Введите ${config.label.toLowerCase()}`}
                              />
                            )}
                            
                            {config.type === 'date' && (
                              <Input
                                id={`placeholder_${key}`}
                                type="date"
                                value={placeholderValues[key] || ''}
                                onChange={(e) => setPlaceholderValues({...placeholderValues, [key]: e.target.value})}
                                required={config.required}
                                className="mt-1"
                              />
                            )}
                            
                            {config.type === 'phone' && (
                              <IMaskInput
                                mask="+7 (000) 000-00-00"
                                value={placeholderValues[key] || ''}
                                onAccept={(value) => setPlaceholderValues({...placeholderValues, [key]: value})}
                                placeholder="+7 (___) ___-__-__"
                                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 mt-1"
                                id={`placeholder_${key}`}
                                type="tel"
                              />
                            )}
                            
                            {config.type === 'email' && (
                              <Input
                                id={`placeholder_${key}`}
                                type="email"
                                value={placeholderValues[key] || ''}
                                onChange={(e) => setPlaceholderValues({...placeholderValues, [key]: e.target.value})}
                                required={config.required}
                                className="mt-1"
                                placeholder={`Введите ${config.label.toLowerCase()}`}
                              />
                            )}
                          </div>
                        );
                      })}
                    </div>

                    {/* Tenant Document Upload (if required by template) */}
                    {selectedTemplate.requires_tenant_document && (
                      <div className="mt-4 p-4 bg-amber-50 border border-amber-200 rounded-lg">
                        <Label className="font-semibold text-amber-900">
                          📄 Удостоверение личности нанимателя
                        </Label>
                        <p className="text-xs text-amber-700 mt-1 mb-3">
                          Вы можете загрузить удостоверение нанимателя сейчас (если есть копия), 
                          или наниматель загрузит его при подписании
                        </p>
                        
                        <div className="flex gap-2 items-center">
                          <Input
                            type="file"
                            accept="image/*,application/pdf"
                            onChange={(e) => {
                              const file = e.target.files[0];
                              if (file) {
                                setTenantDocument(file);
                                // Create preview
                                const reader = new FileReader();
                                reader.onload = () => setTenantDocPreview(reader.result);
                                reader.readAsDataURL(file);
                                toast.success('Документ выбран');
                              }
                            }}
                            className="flex-1"
                          />
                          {tenantDocument && (
                            <Button
                              type="button"
                              variant="outline"
                              size="sm"
                              onClick={() => {
                                setTenantDocument(null);
                                setTenantDocPreview(null);
                              }}
                            >
                              Удалить
                            </Button>
                          )}
                        </div>
                        
                        {tenantDocPreview && (
                          <div className="mt-2">
                            <p className="text-xs text-green-600">✓ Документ загружен: {tenantDocument.name}</p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )}

                {/* Tenant Info - Optional Fields (only show if no template selected) */}
                {!selectedTemplate && (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between border-b pb-2">
                      <div>
                        <h3 className="font-semibold text-neutral-900">Наниматель (Клиент)</h3>
                        <p className="text-xs text-neutral-500">Необязательные поля - клиент заполнит при подписании</p>
                      </div>
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        onClick={() => setShowOptionalFields(!showOptionalFields)}
                        className="text-sm"
                      >
                        {showOptionalFields ? '▼ Скрыть' : '▶ Показать опциональные поля'}
                      </Button>
                    </div>
                  
                  {showOptionalFields && (
                    <div className="space-y-4 p-4 bg-gray-50 rounded-lg border border-gray-200">
                      <div>
                        <Label htmlFor="tenant_name">ФИО нанимателя</Label>
                        <Input
                          id="tenant_name"
                          value={templateData.tenant_name}
                          onChange={(e) => handleFieldChange('tenant_name', e.target.value)}
                          data-testid="tenant-name-input"
                          className="mt-1"
                          placeholder="Оставьте пустым, если клиент заполнит сам"
                        />
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <Label htmlFor="tenant_phone">Телефон</Label>
                          <IMaskInput
                            mask="+7 (000) 000-00-00"
                            value={templateData.tenant_phone}
                            onAccept={(value) => handleFieldChange('tenant_phone', value)}
                            placeholder="+7 (___) ___-__-__"
                            className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 mt-1"
                            id="tenant_phone"
                            type="tel"
                            data-testid="tenant-phone-input"
                          />
                        </div>
                        <div>
                          <Label htmlFor="tenant_email">Email</Label>
                          <Input
                            id="tenant_email"
                            type="email"
                            value={templateData.tenant_email}
                            onChange={(e) => handleFieldChange('tenant_email', e.target.value)}
                            data-testid="tenant-email-input"
                            className="mt-1"
                            placeholder="Опционально"
                          />
                        </div>
                      </div>
                      
                      <div>
                        <Label>Удостоверение личности клиента (опционально)</Label>
                        <p className="text-xs text-neutral-500 mb-3">Если есть документ клиента, можете загрузить. Иначе клиент загрузит сам.</p>
                        
                        {tenantDocPreview && (
                          <div className="mb-6">
                            <div className="bg-green-50 border-l-4 border-green-500 p-3 rounded-r mb-4">
                              <div className="flex items-center gap-2 text-green-800">
                                <CheckCircle className="h-5 w-5" />
                                <span className="font-semibold">Документ загружен успешно</span>
                              </div>
                            </div>
                            <div className="mb-4">
                              <img
                                src={tenantDocPreview}
                                alt=""
                                className="w-full rounded-lg border-2 border-green-200 shadow-md block"
                              />
                            </div>
                          </div>
                        )}
                        
                        <Label htmlFor="tenant_doc" className="cursor-pointer">
                          <Button type="button" variant="outline" className="w-full" asChild>
                            <span>
                              <Upload className="mr-2 h-4 w-4" />
                              {tenantDocument ? 'Изменить документ клиента' : 'Загрузить документ клиента'}
                            </span>
                          </Button>
                          <Input
                            id="tenant_doc"
                            type="file"
                            accept="image/*,.pdf"
                            onChange={handleTenantDocUpload}
                            className="hidden"
                          />
                        </Label>
                        <p className="text-xs text-neutral-500 mt-1">Поддерживаются: JPEG, PNG, PDF</p>
                      </div>
                    </div>
                  )}
                  </div>
                )}

                {/* Property Details (only show if no template selected) */}
                {!selectedTemplate && (
                <div className="space-y-4">
                  <h3 className="font-semibold text-neutral-900 border-b pb-2">Описание и адрес квартиры</h3>
                  <div>
                    <Label htmlFor="property_address">Адрес квартиры *</Label>
                    <Input
                      id="property_address"
                      value={templateData.property_address}
                      onChange={(e) => handleFieldChange('property_address', e.target.value)}
                      required
                      data-testid="property-address-input"
                      className="mt-1"
                      placeholder="г. Алматы, ул. ..."
                    />
                  </div>
                </div>
                )}

                {/* Financial Terms */}
                {!selectedTemplate && (
                <div className="space-y-4">
                  <h3 className="font-semibold text-neutral-900 border-b pb-2">Финансовые условия</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="rent_amount">Цена в сутки *</Label>
                      <Input
                        id="rent_amount"
                        type="number"
                        value={templateData.rent_amount}
                        onChange={(e) => handleFieldChange('rent_amount', e.target.value)}
                        required
                        data-testid="rent-amount-input"
                        className="mt-1"
                        placeholder="10000"
                      />
                    </div>
                    <div>
                      <Label htmlFor="security_deposit">Обеспечительный депозит</Label>
                      <Input
                        id="security_deposit"
                        type="number"
                        value={templateData.security_deposit}
                        onChange={(e) => handleFieldChange('security_deposit', e.target.value)}
                        data-testid="security-deposit-input"
                        className="mt-1"
                        placeholder="5000"
                      />
                    </div>
                  </div>
                  <div>
                    <Label htmlFor="days_count">Количество суток (рассчитывается автоматически)</Label>
                    <Input
                      id="days_count"
                      type="number"
                      value={templateData.days_count}
                      readOnly
                      disabled
                      data-testid="days-count-input"
                      className="mt-1 bg-neutral-100 cursor-not-allowed"
                    />
                    <p className="text-xs text-neutral-500 mt-1">С 14:00 даты заселения до 12:00 даты выселения</p>
                  </div>
                  {templateData.rent_amount && templateData.days_count && (
                    <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
                      <p className="text-sm text-blue-900">
                        <strong>Полная стоимость:</strong> {parseInt(templateData.rent_amount) * parseInt(templateData.days_count)} {templateData.rent_currency}
                      </p>
                    </div>
                  )}
                </div>
                )}

                {/* Dates */}
                {!selectedTemplate && (
                <div className="space-y-4">
                  <h3 className="font-semibold text-neutral-900 border-b pb-2">Даты заселения и выселения</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="move_in_date">Дата заселения *</Label>
                      <Input
                        id="move_in_date"
                        type="date"
                        value={templateData.move_in_date}
                        onChange={(e) => handleFieldChange('move_in_date', e.target.value)}
                        required
                        data-testid="move-in-date-input"
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <Label htmlFor="move_out_date">Дата выселения *</Label>
                      <Input
                        id="move_out_date"
                        type="date"
                        value={templateData.move_out_date}
                        onChange={(e) => handleFieldChange('move_out_date', e.target.value)}
                        required
                        data-testid="move-out-date-input"
                        className="mt-1"
                      />
                    </div>
                  </div>
                </div>
                )}

                {/* Submit Buttons */}
                <div className="flex gap-3 pt-4 border-t">
                  <Button
                    type="submit"
                    disabled={loading}
                    data-testid="save-contract-button"
                    className="flex-1"
                  >
                    {loading ? t('common.loading') : 'Сохранить договор'}
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => navigate('/dashboard')}
                    data-testid="cancel-button"
                  >
                    {t('common.cancel')}
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default CreateContractPage;